# Use root/example as user/password credentials
version: "3.1"

services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongoDB:/data/db
    ports:
      - 27017:27017
    networks: 
      - camera-network
    
  camera-api:
    image: camera-api
    restart: always
    ports:
      - 9091:8080
    networks: 
      - camera-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9092:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo-db
    networks: 
      - camera-network

networks: 
  camera-network:
    name: camera-network